Improve scripts
readability and logic.

Fixed an issue where script/setup would overwrite a good .env file with 
the example.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,36 +1,36 @@
 #!/bin/sh
 
 #
-# Use these scripts to (test and) deploy the octodns config in this repository.
+# Use these scripts when developing and testing changes to solvahol/dns.
 #
-# - script/bootstrap: Ensure this workspace is ready to test and deploy our
-#   DNS configurations.
+# - script/bootstrap: Ensure this workspace is ready.
 #
 
-# Change directory to the root of this repository. Also, ensure we have Git.
-cd "$(git rev-parse --show-toplevel)" || return
+# Work from the root of a Git repository.
+cd "$(git rev-parse --show-toplevel)" || \
+echo "WARN: Unable to cd to repository root."
 
 # Required commands are available.
 for _thiscmd in git python3 yamllint shellcheck; do
-  command -v ${_thiscmd} >/dev/null 2>&1 || echo "WARN: Missing ${_thiscmd}"
+  command -v ${_thiscmd} >/dev/null 2>&1 || echo "WARN: Missing ${_thiscmd}."
 done
 
 # Required files are present, readable, and not empty.
 for _thisfile in requirements.txt public.yaml .config; do
   if [ ! -s "${_thisfile}" ] && [ ! -r "${_thisfile}" ]; then
-    echo "WARN: Missing ${_thisfile}"
+    echo "WARN: Missing ${_thisfile}."
   fi
 done
 
 # Set environment variables.
-. ./.config
+. ./.config || echo "WARN: Unable to run .config."
 
 # Ensure Docker is present and working; Pull the image we'll use.
-if command -v docker >/dev/null 2>&1; then
+if command -v docker >/dev/null 2>&1 && [ -n "${_image}" ]; then
   docker pull "${_image}"
 else
   echo ""
-  echo "Did not find docker. Run these commands:"
+  echo "Hmm. Something isn't right. Does this work for you?:"
   echo "docker pull \"${_image}\""
   echo ""
 fi
